# Generated by Django 5.0.4 on 2024-05-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('active', models.BooleanField(verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('active', models.BooleanField(verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Gamer',
                'verbose_name_plural': 'Gamers',
                'db_table': 'gamers',
            },
        ),
        migrations.CreateModel(
            name='Playing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.game')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.gamer')),
            ],
            options={
                'verbose_name': 'Playing',
                'verbose_name_plural': 'Playing',
                'db_table': 'playing',
            },
        ),
    ]
